--Create database
CREATE DATABASE SP_ETL
go
Use SP_ETL ;


--Create Source Table
CREATE  TABLE  CUSTOMER_SRC
(
CUSTOMERID	INT	IDENTITY (1,1) PRIMARY KEY	,
FULLNAME	VARCHAR(100)		,
BIRTHDATE	DATETIME		,
MARITALSTATUS	VARCHAR(100)		,
GENDER	VARCHAR(100)	
);	

--Create Target Table
CREATE  TABLE  CUSTOMER_TRG
(
CUSTOMERKEY	INT	IDENTITY (100,1) PRIMARY KEY	,
CUSTOMERID	INT		,
FULLNAME	VARCHAR(100)		,
BIRTHDATE	DATETIME		,
MARITALSTATUS	VARCHAR(100)		,
GENDER	VARCHAR(100)		
);	

--Insert data in Source Table CUSTOMER_SRC

INSERT INTO [DBO].CUSTOMER_SRC ([FULLNAME],[BIRTHDATE],[MARITALSTATUS],[GENDER])
     VALUES
           ('John D','1987-11-08 16:46:54.480','M','F')
GO
INSERT INTO [DBO].CUSTOMER_SRC ([FULLNAME],[BIRTHDATE],[MARITALSTATUS],[GENDER])
     VALUES
           ('Amit K','1999-12-03 16:46:54.480','S','M')
GO

INSERT INTO [DBO].CUSTOMER_SRC ([FULLNAME],[BIRTHDATE],[MARITALSTATUS],[GENDER])
     VALUES
           ('Ronald R','1897-01-23 16:46:54.480','S','M')
GO

INSERT INTO [DBO].CUSTOMER_SRC ([FULLNAME],[BIRTHDATE],[MARITALSTATUS],[GENDER])
     VALUES
           ('Pooja D','1974-11-07 16:46:54.480','S','M')
GO

INSERT INTO [DBO].CUSTOMER_SRC ([FULLNAME],[BIRTHDATE],[MARITALSTATUS],[GENDER])
     VALUES
           ('Elon M','1994-11-04 16:46:54.480','S','M')
GO



--Check Data in source and target table
SELECT * FROM CUSTOMER_SRC ;
SELECT * FROM CUSTOMER_TRG ;




--Create procedure to load data from source table to target table
CREATE PROCEDURE SP_ETL
AS
INSERT INTO SP_ETL.DBO.CUSTOMER_TRG  (E.CUSTOMERID,E.[FULLNAME]
           ,E.[BIRTHDATE]
           ,E.[MARITALSTATUS]
           ,E.[GENDER]
		  
          )
SELECT CUSTOMERID	,
FULLNAME	,
BIRTHDATE	,
MARITALSTATUS	,
GENDER
 FROM SP_ETL.DBO.CUSTOMER_SRC
 WHERE CUSTOMERID IN (
SELECT CUSTOMERID FROM (

SELECT E.CUSTOMERID,E.[FULLNAME]
           ,E.[MARITALSTATUS]
            FROM SP_ETL.DBO.CUSTOMER_SRC E

EXCEPT  --EXCEPT returns only rows, which are not available in the second SELECT statement,
        --Here we are comparing FULLNAME, MARITALSTATUS column os source and target table

SELECT  T.CUSTOMERID
            ,T.[FULLNAME]--SCD2
           ,T.[MARITALSTATUS]--SCD2
          
           FROM SP_ETL.DBO.CUSTOMER_TRG T
WHERE T.CUSTOMERKEY IN (SELECT MAX(T.CUSTOMERKEY) FROM SP_ETL.DBO.CUSTOMER_TRG T GROUP BY T.CUSTOMERID) AND T.CUSTOMERID IS NOT NULL) AS A) ;


UPDATE T
	SET 
T.GENDER=S.GENDER, --SCD1
T.BIRTHDATE=S.BIRTHDATE--SCD1

FROM
	SP_ETL.DBO.CUSTOMER_SRC S LEFT JOIN SP_ETL.DBO.CUSTOMER_TRG T ON T.CUSTOMERID = S.CUSTOMERID
WHERE

T.GENDER<>S.GENDER OR
T.BIRTHDATE<>S.BIRTHDATE
AND T.CUSTOMERKEY IN (SELECT MAX (T.CUSTOMERKEY) FROM SP_ETL.DBO.CUSTOMER_TRG T GROUP BY T.CUSTOMERID) AND T.CUSTOMERID IS NOT NULL  ;







--Execute Procedure for initial load 
EXEC  SP_ETL ;


--Check Data in source and target table
SELECT * FROM SP_ETL.DBO.CUSTOMER_SRC ;
SELECT * FROM SP_ETL.DBO.CUSTOMER_TRG ;


--Update data in source table CUSTOMER_SRC
--I
UPDATE SP_ETL.DBO.CUSTOMER_SRC SET FULLNAME = 'John W'
WHERE CUSTOMERID = '1';
--U
UPDATE SP_ETL.DBO.CUSTOMER_SRC SET BIRTHDATE = '1995-01-13 16:46:54.480'
WHERE CUSTOMERID = '2';
--I
UPDATE SP_ETL.DBO.CUSTOMER_SRC SET MARITALSTATUS = 'M'
WHERE CUSTOMERID = '3';
--U
UPDATE SP_ETL.DBO.CUSTOMER_SRC SET [GENDER] = 'F'
WHERE CUSTOMERID = '4';



--Execute Procedure to load data at target table 
EXEC SP_ETL ;


--Compare Data in source and target table
SELECT * FROM CUSTOMER_SRC ;
SELECT * FROM CUSTOMER_TRG ;



--Compare Current records in source and target table
SELECT CUSTOMERID	,
FULLNAME	,
BIRTHDATE	,
MARITALSTATUS	,
GENDER	
FROM CUSTOMER_TRG 
Where 
	CUSTOMERKEY IN (SELECT MAX (CUSTOMERKEY) FROM SP_ETL.DBO.CUSTOMER_TRG  GROUP BY CUSTOMERID) -- To find latest record to Cutomer 


Except  --EXCEPT returns only rows, which are not available in the second SELECT statement. 


SELECT CUSTOMERID	,
FULLNAME	,
BIRTHDATE	,
MARITALSTATUS	,
GENDER	
FROM CUSTOMER_SRC  ;


