
SELECT * from CUSTOMER_BILL_DTS_SRC;

SELECT * from CUSTOMER_BILL_DTS_TRG1;

SELECT * from CUSTOMER_BILL_DTS_TRG2;



Truncate table CUSTOMER_BILL_DTS_TRG1;
Truncate table CUSTOMER_BILL_DTS_TRG2;

Select COUNT(*) from CUSTOMER_BILL_DTS_SRC
where CUSTOMER_GENDER = 'M';

Select COUNT(*) from CUSTOMER_BILL_DTS_TRG1
where CUSTOMER_GENDER = 'M';

Select COUNT(*) from CUSTOMER_BILL_DTS_SRC
where CUSTOMER_GENDER = 'F';

Select COUNT(*) from CUSTOMER_BILL_DTS_TRG2
where CUSTOMER_GENDER = 'F';
